export const page_routes = {
  home: "/",
  resourceCenter: "/resources",
  manageBlogs: "/dashboard/blogs",
  manageAdmins: "/dashboard/admins",
  adminMessages: "/dashboard/messages",
  dashboard: "/dashboard",
  contactUs: "/contactus",
  secure: "/secure",
  Integrations: "/integrations",
  ITSecurity: "/security",
  Consulting: "/consulting",
  Offshore: "/offshore",
  Delivery: "/delivery",
  staffing: "/staffing",
};
