export const page_routes = {
    home: "/",
    about: "/about",
    resourceCenter: "/resources",
    manageBlogs: "/dashboard/blogs",
    manageAdmins: "/dashboard/admins",
    adminMessages: "/dashboard/messages",
    dashboard: "/dashboard",
    contactUs: "/contactus",
    secure: "/secure",
    ITSecurity: "/security",
    Consulting: "/consulting",
    Offshore: "/offshore",
    Delivery: "/delivery",
    staffing: "/staffing",
};
