export const blogResource = [
  {
    id: 1,
    blogType: "Article",
    blogHeader: "Test",
    blogURl: "#",
    blogTextResource: "this is just a test",
    blogHeroUrl: "",
  },
  {
    id: 2,
    blogType: "Article",
    blogHeader: "Test",
    blogURl: "#",
    blogTextResource: "this is just a test",
    blogHeroUrl: "",
  },
  {
    id: 3,
    blogType: "Article",
    blogHeader: "Test",
    blogURl: "#",
    blogTextResource: "this is just a test",
    blogHeroUrl: "",
  },
  {
    id: 4,
    blogType: "Article",
    blogHeader: "Test",
    blogURl: "#",
    blogTextResource: "this is just a test",
    blogHeroUrl: "",
  },
  {
    id: 5,
    blogType: "Article",
    blogHeader: "Test",
    blogURl: "#",
    blogTextResource: "this is just a test",
    blogHeroUrl: "",
  },
  {
    id: 6,
    blogType: "Article",
    blogHeader: "Test",
    blogURl: "#",
    blogTextResource: "this is just a test",
    blogHeroUrl: "",
  },
  {
    id: 7,
    blogType: "Article",
    blogHeader: "Test",
    blogURl: "#",
    blogTextResource: "this is just a test",
    blogHeroUrl: "",
  },
  {
    id: 8,
    blogType: "Article",
    blogHeader: "Test",
    blogURl: "#",
    blogTextResource: "this is just a test",
    blogHeroUrl: "",
  },
];
export const articleResource = [
  {
    id: 1,
    articleType: "Article",
    articleHeader: "Test",
    articleURl: "#",
    articleTextResource: "this is just a test",
    articleHeroUrl: "",
  },
  {
    id: 2,
    articleType: "Article",
    articleHeader: "Test",
    articleURl: "#",
    articleTextResource: "this is just a test",
    articleHeroUrl: "",
  },
  {
    id: 3,
    articleType: "Article",
    articleHeader: "Test",
    articleURl: "#",
    articleTextResource: "this is just a test",
    articleHeroUrl: "",
  },
  {
    id: 4,
    articleType: "Article",
    articleHeader: "Test",
    articleURl: "#",
    articleTextResource: "this is just a test",
    articleHeroUrl: "",
  },
  {
    id: 5,
    articleType: "Article",
    articleHeader: "Test",
    articleURl: "#",
    articleTextResource: "this is just a test",
    articleHeroUrl: "",
  },
  {
    id: 6,
    articleType: "Article",
    articleHeader: "Test",
    articleURl: "#",
    articleTextResource: "this is just a test",
    articleHeroUrl: "",
  },
  {
    id: 7,
    articleType: "Article",
    articleHeader: "Test",
    articleURl: "#",
    articleTextResource: "this is just a test",
    articleHeroUrl: "",
  },
  {
    id: 8,
    articleType: "Article",
    articleHeader: "Test",
    articleURl: "#",
    articleTextResource: "this is just a test",
    articleHeroUrl: "",
  },
];

export const newsResource = [
  {
    id: 1,
    newsType: "news",
    newsHeader: "Test",
    newsURl: "#",
    newsTextResource: "this is just a test",
    newsHeroUrl: "",
  },
  {
    id: 2,
    newsType: "news",
    newsHeader: "Test",
    newsURl: "#",
    newsTextResource: "this is just a test",
    newsHeroUrl: "",
  },
  {
    id: 3,
    newsType: "news",
    newsHeader: "Test",
    newsURl: "#",
    newsTextResource: "this is just a test",
    newsHeroUrl: "",
  },
  {
    id: 4,
    newsType: "news",
    newsHeader: "Test",
    newsURl: "#",
    newsTextResource: "this is just a test",
    newsHeroUrl: "",
  },
  {
    id: 5,
    newsType: "news",
    newsHeader: "Test",
    newsURl: "#",
    newsTextResource: "this is just a test",
    newsHeroUrl: "",
  },
  {
    id: 6,
    newsType: "news",
    newsHeader: "Test",
    newsURl: "#",
    newsTextResource: "this is just a test",
    newsHeroUrl: "",
  },
  {
    id: 7,
    newsType: "news",
    newsHeader: "Test",
    newsURl: "#",
    newsTextResource: "this is just a test",
    articleHeroUrl: "",
  },
  {
    id: 8,
    articleType: "Article",
    articleHeader: "Test",
    articleURl: "#",
    articleTextResource: "this is just a test",
    articleHeroUrl: "",
  },
];
